### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by christophe77** [yoannchb-pro/google-img-scrap#1]
Hi, I want to try your module on a typescript project, can you export the typings?

**Comment by yoannchb-pro** [comment]
Bonjour, 
J'aimerais pouvoir vous aider là dessus mais il se trouve que je ne sais pas programmer en typescript.
Vous pouvez participer au projet si vous voulez.
Si je trouves le temps je vais essayer de me renseigner pour passer mon module en typescript.

Hello,
I wish I could help you on that but I happen to not know how to program in typescript.
You can participate in the project if you want.
If I find the time I will try to find out how to pass my module in typescript.

**Comment by christophe77** [comment]
Pas besoin de le passer en typescript, il faut juste ajouter un fichier de définitions. Je vais le faire et je ferai un pull request.

**Comment by yoannchb-pro** [comment]
Ok parfait merci beaucoup. Je vais publish le paquet sur npm et je vous ai ajouté aux contributeurs.
