### ISSUE TITLE
cannot get result

### ISSUE THREAD

**Issue by wansky05** [yoannchb-pro/google-img-scrap#10]
GOOGL_IMG_SCRAP return result : [ ]

**Comment by tatsumara** [comment]
can confirm, same thing on my end

**Comment by yoannchb-pro** [comment]
Hello, I just saw that my package isn't working anymore I think it's due to an update from google image side. I'll try to fix it during this week. Thx y for telling me.

**Comment by yoannchb-pro** [comment]
fixed in v1.1.1
