### ISSUE TITLE
Possibility to set a result limit

### ISSUE THREAD

**Issue by christophe77** [yoannchb-pro/google-img-scrap#2]
Is it posible to add a result limit for a query on module side?

**Comment by yoannchb-pro** [comment]
Bonjour, il n'est pas possible de mettre une limite de résultat du coté module. En effet, lorsque je scrap google image je retourne tout les résultats. Mais il est possible de votre côté de récupérer seulement une partie de ces résultats.

Hello, it is not possible to set a result limit on the module side. Indeed, when I scrap google image I return all the results. But it is possible on your side to recover only part of these results.

**Comment by christophe77** [comment]
solved with 1.0.6
