### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by AJ-OP2311** [yoannchb-pro/google-img-scrap#5]
![unknown](https://user-images.githubusercontent.com/95399901/190847261-b2b877cc-9587-4f08-bd93-92afd552bfa1.png)

**Comment by yoannets** [comment]
Hello,
This error is due (as it say) to too many request on google. The only way to avoid it is to use proxy or to set a tiemout between request. But I think the better solution is to register data in json file or in a database if you are scrapping the same datas every times.

**Comment by yoannets** [comment]
There are other way that you can found on google by searching thing like this "google scrapping request limit"

**Comment by AJ-OP2311** [comment]
> Hello, This error is due (as it say) to too many request on google. The only way to avoid it is to use proxy or to set a tiemout between request. But I think the better solution is to register data in json file or in a database if you are scrapping the same datas every times.

how to use proxy?

**Comment by yoannchb-pro** [comment]
Lot of differents way on google. But you also need to find working proxies. I don’t think it’s the best solution. Just try to reduce the numbers of request or register result in database should be better.

**Comment by yoannchb-pro** [comment]
fixed in v1.0.9 with proxy option
