### ISSUE TITLE
axios_1.default is not a function?

### ISSUE THREAD

**Issue by mobeets** [yoannchb-pro/google-img-scrap#9]
Hi, I'm getting the following error when calling this:

```javascript
const test = await GOOGLE_IMG_SCRAP({
    search: "cats",
});
console.log(test);
```

The error is:
```
Uncaught (in promise) TypeError: axios_1.default is not a function
    scrapGoogleImagesScriptsTag parseGoogleImages.ts:17
    __awaiter bundle.js:3372
    __awaiter bundle.js:3354
    scrapGoogleImagesScriptsTag bundle.js:3395
    parseGoogleImages parseGoogleImages.ts:65
    __awaiter bundle.js:3372
    __awaiter bundle.js:3354
    parseGoogleImages bundle.js:3429
    GOOGLE_IMG_SCRAP index.ts:71
    __awaiter bundle.js:3530
    __awaiter bundle.js:3512
    GOOGLE_IMG_SCRAP bundle.js:3592
    handleSubmit hooks.js:29
    React 23
    js index.js:6
    factory react refresh:6
    Webpack 3
```

I'm new to using React and npm, so it's possible this is due to a very obvious error on my part, but I'm curious if you have any ideas what I might be doing wrong.

**Comment by yoannchb-pro** [comment]
I don't know what exactly is this error but if you are using it directly in react it will not work because react is a frontend framework you will need to set up a backend to use this package with expressjs for example. Are you using it directly in react ?

**Comment by mobeets** [comment]
Oh okay I see, I don't have a backend framework, so that's probably the issue. Thanks for the info!

**Comment by yoannchb-pro** [comment]
Haha no problem you can make one very fast with expressjs (only 20 lines of codes)
